from holosoma.config_types.algo import (
    FastSACAlgoConfig,
    FastSACConfig,
    LayerConfig,
    ModuleConfig,
    OptimizerConfig,
    PPOAlgoConfig,
    PPOConfig,
    PPOModuleDictConfig,
)

ppo = PPOAlgoConfig(
    _target_="holosoma.agents.ppo.ppo.PPO",
    _recursive_=False,
    config=PPOConfig(
        num_learning_epochs=8,
        num_mini_batches=4,
        clip_param=0.2,
        gamma=0.99,
        lam=0.95,
        value_loss_coef=1.0,
        entropy_coef=0.01,
        actor_learning_rate=1e-5,
        actor_optimizer=OptimizerConfig(_target_="torch.optim.AdamW", weight_decay=0.001),
        critic_learning_rate=1e-5,
        critic_optimizer=OptimizerConfig(_target_="torch.optim.AdamW", weight_decay=0.001),
        max_grad_norm=1.0,
        schedule="adaptive",
        desired_kl=0.01,
        use_symmetry=True,
        symmetry_actor_coef=1.0,
        symmetry_critic_coef=0.0,
        num_steps_per_env=24,
        save_interval=100,
        load_optimizer=True,
        init_noise_std=0.8,
        num_learning_iterations=1000000,
        init_at_random_ep_len=True,
        empirical_normalization=False,
        eval_callbacks=None,
        module_dict=PPOModuleDictConfig(
            actor=ModuleConfig(
                type="MLP",
                input_dim=["actor_obs"],
                output_dim=["robot_action_dim"],
                layer_config=LayerConfig(hidden_dims=[512, 256, 128], activation="ELU"),
            ),
            critic=ModuleConfig(
                type="MLP",
                input_dim=["critic_obs"],
                output_dim=[1],
                layer_config=LayerConfig(hidden_dims=[512, 256, 128], activation="ELU"),
            ),
        ),
    ),
)

fast_sac = FastSACAlgoConfig(
    _target_="holosoma.agents.fast_sac.fast_sac_agent.FastSACAgent",
    _recursive_=False,
    config=FastSACConfig(
        num_learning_iterations=50000,
        critic_learning_rate=3e-4,
        actor_learning_rate=3e-4,
        alpha_learning_rate=3e-4,
        buffer_size=1024,
        num_steps=1,
        gamma=0.97,
        tau=0.125,
        batch_size=8192,
        learning_starts=10,
        policy_frequency=4,
        num_updates=8,
        target_entropy_ratio=0.0,
        num_atoms=101,
        v_min=-20.0,
        v_max=20.0,
        critic_hidden_dim=768,
        actor_hidden_dim=512,
        use_symmetry=True,
        alpha_init=0.001,
        use_autotune=True,
        use_tanh=True,
        log_std_max=0.0,
        log_std_min=-5.0,
        compile=True,
        obs_normalization=True,
        use_layer_norm=True,
        num_q_networks=2,
        max_grad_norm=0.0,
        amp=True,
        amp_dtype="bf16",
        weight_decay=0.001,
        save_interval=1000,
        logging_interval=100,
        encoder_obs_key="perception_obs",
        encoder_obs_shape=(1, 13, 9),
        use_cnn_encoder=False,
        actor_obs_keys=["actor_obs"],
        critic_obs_keys=["critic_obs"],
    ),
)

DEFAULTS = {
    "ppo": ppo,
    "fast_sac": fast_sac,
}
