from dataclasses import replace

from holosoma.config_types.robot import (
    RobotAssetConfig,
    RobotBridgeConfig,
    RobotConfig,
    RobotControlConfig,
    RobotInitState,
)

g1_29dof = RobotConfig(
    num_bodies=32,
    dof_obs_size=29,
    actions_dim=29,
    policy_obs_dim=-1,
    critic_obs_dim=-1,
    algo_obs_dim_dict={},
    key_bodies=["left_foot_contact_point", "right_foot_contact_point"],
    num_feet=2,
    foot_body_name="ankle_roll_link",
    foot_height_name="foot_contact_point",
    knee_name="knee_link",
    torso_name="torso_link",
    dof_names=[
        "left_hip_pitch_joint",
        "left_hip_roll_joint",
        "left_hip_yaw_joint",
        "left_knee_joint",
        "left_ankle_pitch_joint",
        "left_ankle_roll_joint",
        "right_hip_pitch_joint",
        "right_hip_roll_joint",
        "right_hip_yaw_joint",
        "right_knee_joint",
        "right_ankle_pitch_joint",
        "right_ankle_roll_joint",
        "waist_yaw_joint",
        "waist_roll_joint",
        "waist_pitch_joint",
        "left_shoulder_pitch_joint",
        "left_shoulder_roll_joint",
        "left_shoulder_yaw_joint",
        "left_elbow_joint",
        "left_wrist_roll_joint",
        "left_wrist_pitch_joint",
        "left_wrist_yaw_joint",
        "right_shoulder_pitch_joint",
        "right_shoulder_roll_joint",
        "right_shoulder_yaw_joint",
        "right_elbow_joint",
        "right_wrist_roll_joint",
        "right_wrist_pitch_joint",
        "right_wrist_yaw_joint",
    ],
    upper_dof_names=[
        "waist_yaw_joint",
        "waist_roll_joint",
        "waist_pitch_joint",
        "left_shoulder_pitch_joint",
        "left_shoulder_roll_joint",
        "left_shoulder_yaw_joint",
        "left_elbow_joint",
        "left_wrist_roll_joint",
        "left_wrist_pitch_joint",
        "left_wrist_yaw_joint",
        "right_shoulder_pitch_joint",
        "right_shoulder_roll_joint",
        "right_shoulder_yaw_joint",
        "right_elbow_joint",
        "right_wrist_roll_joint",
        "right_wrist_pitch_joint",
        "right_wrist_yaw_joint",
    ],
    upper_left_arm_dof_names=[
        "left_shoulder_pitch_joint",
        "left_shoulder_roll_joint",
        "left_shoulder_yaw_joint",
        "left_elbow_joint",
        "left_wrist_roll_joint",
        "left_wrist_pitch_joint",
        "left_wrist_yaw_joint",
    ],
    upper_right_arm_dof_names=[
        "right_shoulder_pitch_joint",
        "right_shoulder_roll_joint",
        "right_shoulder_yaw_joint",
        "right_elbow_joint",
        "right_wrist_roll_joint",
        "right_wrist_pitch_joint",
        "right_wrist_yaw_joint",
    ],
    lower_dof_names=[
        "left_hip_pitch_joint",
        "left_hip_roll_joint",
        "left_hip_yaw_joint",
        "left_knee_joint",
        "left_ankle_pitch_joint",
        "left_ankle_roll_joint",
        "right_hip_pitch_joint",
        "right_hip_roll_joint",
        "right_hip_yaw_joint",
        "right_knee_joint",
        "right_ankle_pitch_joint",
        "right_ankle_roll_joint",
    ],
    has_torso=True,
    has_upper_body_dof=True,
    left_ankle_dof_names=["left_ankle_pitch_joint", "left_ankle_roll_joint"],
    right_ankle_dof_names=["right_ankle_pitch_joint", "right_ankle_roll_joint"],
    knee_dof_names=["left_knee_joint", "right_knee_joint"],
    hips_dof_names=[
        "left_hip_pitch_joint",
        "left_hip_roll_joint",
        "left_hip_yaw_joint",
        "right_hip_pitch_joint",
        "right_hip_roll_joint",
        "right_hip_yaw_joint",
    ],
    dof_pos_lower_limit_list=[
        -2.5307,
        -0.5236,
        -2.7576,
        -0.087267,
        -0.87267,
        -0.2618,
        -2.5307,
        -2.9671,
        -2.7576,
        -0.087267,
        -0.87267,
        -0.2618,
        -2.618,
        -0.52,
        -0.52,
        -3.0892,
        -1.5882,
        -2.618,
        -1.0472,
        -1.972222054,
        -1.61443,
        -1.61443,
        -3.0892,
        -2.2515,
        -2.618,
        -1.0472,
        -1.972222054,
        -1.61443,
        -1.61443,
    ],
    dof_pos_upper_limit_list=[
        2.8798,
        2.9671,
        2.7576,
        2.8798,
        0.5236,
        0.2618,
        2.8798,
        0.5236,
        2.7576,
        2.8798,
        0.5236,
        0.2618,
        2.618,
        0.52,
        0.52,
        2.6704,
        2.2515,
        2.618,
        2.0944,
        1.972222054,
        1.61443,
        1.61443,
        2.6704,
        1.5882,
        2.618,
        2.0944,
        1.972222054,
        1.61443,
        1.61443,
    ],
    dof_vel_limit_list=[
        32.0,
        20.0,
        32.0,
        20.0,
        37.0,
        37.0,  # left leg (hip_pitch, hip_roll, hip_yaw, knee, ankle_pitch, ankle_roll)
        32.0,
        20.0,
        32.0,
        20.0,
        37.0,
        37.0,  # right leg
        32.0,
        37.0,
        37.0,  # waist (yaw, roll, pitch)
        37.0,
        37.0,
        37.0,
        37.0,  # left arm (shoulder_pitch, shoulder_roll, shoulder_yaw, elbow)
        37.0,
        22.0,
        22.0,  # left wrist (roll, pitch, yaw)
        37.0,
        37.0,
        37.0,
        37.0,  # right arm
        37.0,
        22.0,
        22.0,
    ],  # right wrist
    dof_effort_limit_list=[
        88.0,
        139.0,
        88.0,
        139.0,
        50.0,
        50.0,  # left leg (hip_pitch, hip_roll, hip_yaw, knee, ankle_pitch, ankle_roll)
        88.0,
        139.0,
        88.0,
        139.0,
        50.0,
        50.0,  # right leg
        88.0,
        50.0,
        50.0,  # waist (yaw, roll, pitch)
        25.0,
        25.0,
        25.0,
        25.0,  # left arm (shoulder_pitch, shoulder_roll, shoulder_yaw, elbow)
        25.0,
        5.0,
        5.0,  # left wrist (roll, pitch, yaw)
        25.0,
        25.0,
        25.0,
        25.0,  # right arm
        25.0,
        5.0,
        5.0,
    ],  # right wrist
    dof_armature_list=[
        0.010177520,
        0.025101925,
        0.010177520,
        0.025101925,
        0.007219450,
        0.007219450,  # left leg
        0.010177520,
        0.025101925,
        0.010177520,
        0.025101925,
        0.007219450,
        0.007219450,  # right leg
        0.010177520,
        0.007219450,
        0.007219450,  # waist
        0.003609725,
        0.003609725,
        0.003609725,
        0.003609725,  # left arm
        0.003609725,
        0.00425,
        0.00425,  # left wrist
        0.003609725,
        0.003609725,
        0.003609725,
        0.003609725,  # right arm
        0.003609725,
        0.00425,
        0.00425,
    ],  # right wrist
    dof_joint_friction_list=[
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0,
    ],
    body_names=[
        "pelvis",
        "left_hip_pitch_link",
        "left_hip_roll_link",
        "left_hip_yaw_link",
        "left_knee_link",
        "left_ankle_pitch_link",
        "left_ankle_roll_link",
        "left_foot_contact_point",
        "right_hip_pitch_link",
        "right_hip_roll_link",
        "right_hip_yaw_link",
        "right_knee_link",
        "right_ankle_pitch_link",
        "right_ankle_roll_link",
        "right_foot_contact_point",
        "waist_yaw_link",
        "waist_roll_link",
        "torso_link",
        "left_shoulder_pitch_link",
        "left_shoulder_roll_link",
        "left_shoulder_yaw_link",
        "left_elbow_link",
        "left_wrist_roll_link",
        "left_wrist_pitch_link",
        "left_wrist_yaw_link",
        "right_shoulder_pitch_link",
        "right_shoulder_roll_link",
        "right_shoulder_yaw_link",
        "right_elbow_link",
        "right_wrist_roll_link",
        "right_wrist_pitch_link",
        "right_wrist_yaw_link",
    ],
    terminate_after_contacts_on=["pelvis", "shoulder", "hip"],
    penalize_contacts_on=["pelvis", "shoulder", "hip"],
    init_state=RobotInitState(
        pos=[0.0, 0.0, 0.8],  # x,y,z [m]
        rot=[0.0, 0.0, 0.0, 1.0],  # x,y,z,w [quat]
        lin_vel=[0.0, 0.0, 0.0],  # x,y,z [m/s]
        ang_vel=[0.0, 0.0, 0.0],  # x,y,z [rad/s]
        default_joint_angles={
            "left_hip_pitch_joint": -0.312,
            "left_hip_roll_joint": 0.0,
            "left_hip_yaw_joint": 0.0,
            "left_knee_joint": 0.669,
            "left_ankle_pitch_joint": -0.363,
            "left_ankle_roll_joint": 0.0,
            "right_hip_pitch_joint": -0.312,
            "right_hip_roll_joint": 0.0,
            "right_hip_yaw_joint": 0.0,
            "right_knee_joint": 0.669,
            "right_ankle_pitch_joint": -0.363,
            "right_ankle_roll_joint": 0.0,
            "waist_yaw_joint": 0.0,
            "waist_roll_joint": 0.0,
            "waist_pitch_joint": 0.0,
            "left_shoulder_pitch_joint": 0.2,
            "left_shoulder_roll_joint": 0.2,
            "left_shoulder_yaw_joint": 0.0,
            "left_elbow_joint": 0.6,
            "left_wrist_roll_joint": 0.0,
            "left_wrist_pitch_joint": 0.0,
            "left_wrist_yaw_joint": 0.0,
            "right_shoulder_pitch_joint": 0.2,
            "right_shoulder_roll_joint": -0.2,
            "right_shoulder_yaw_joint": 0.0,
            "right_elbow_joint": 0.6,
            "right_wrist_roll_joint": 0.0,
            "right_wrist_pitch_joint": 0.0,
            "right_wrist_yaw_joint": 0.0,
        },
    ),
    randomize_link_body_names=[
        "pelvis",
        "left_hip_yaw_link",
        "left_hip_roll_link",
        "left_hip_pitch_link",
        "left_knee_link",
        "right_hip_yaw_link",
        "right_hip_roll_link",
        "right_hip_pitch_link",
        "right_knee_link",
    ],
    waist_dof_names=["waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint"],
    waist_yaw_dof_name="waist_yaw_joint",
    waist_roll_dof_name="waist_roll_joint",
    waist_pitch_dof_name="waist_pitch_joint",
    arm_dof_names=[
        "left_shoulder_pitch_joint",
        "left_shoulder_roll_joint",
        "left_shoulder_yaw_joint",
        "left_elbow_joint",
        "left_wrist_roll_joint",
        "left_wrist_pitch_joint",
        "left_wrist_yaw_joint",
        "right_shoulder_pitch_joint",
        "right_shoulder_roll_joint",
        "right_shoulder_yaw_joint",
        "right_elbow_joint",
        "right_wrist_roll_joint",
        "right_wrist_pitch_joint",
        "right_wrist_yaw_joint",
    ],
    left_arm_dof_names=[
        "left_shoulder_pitch_joint",
        "left_shoulder_roll_joint",
        "left_shoulder_yaw_joint",
        "left_elbow_joint",
        "left_wrist_roll_joint",
        "left_wrist_pitch_joint",
        "left_wrist_yaw_joint",
    ],
    right_arm_dof_names=[
        "right_shoulder_pitch_joint",
        "right_shoulder_roll_joint",
        "right_shoulder_yaw_joint",
        "right_elbow_joint",
        "right_wrist_roll_joint",
        "right_wrist_pitch_joint",
        "right_wrist_yaw_joint",
    ],
    symmetry_joint_names={
        # Lower body joints
        "left_hip_pitch_joint": "right_hip_pitch_joint",
        "left_hip_roll_joint": "right_hip_roll_joint",
        "left_hip_yaw_joint": "right_hip_yaw_joint",
        "left_knee_joint": "right_knee_joint",
        "left_ankle_pitch_joint": "right_ankle_pitch_joint",
        "left_ankle_roll_joint": "right_ankle_roll_joint",
        "right_hip_pitch_joint": "left_hip_pitch_joint",
        "right_hip_roll_joint": "left_hip_roll_joint",
        "right_hip_yaw_joint": "left_hip_yaw_joint",
        "right_knee_joint": "left_knee_joint",
        "right_ankle_pitch_joint": "left_ankle_pitch_joint",
        "right_ankle_roll_joint": "left_ankle_roll_joint",
        # Upper body joints
        "left_shoulder_pitch_joint": "right_shoulder_pitch_joint",
        "left_shoulder_roll_joint": "right_shoulder_roll_joint",
        "left_shoulder_yaw_joint": "right_shoulder_yaw_joint",
        "left_elbow_joint": "right_elbow_joint",
        "left_wrist_roll_joint": "right_wrist_roll_joint",
        "left_wrist_pitch_joint": "right_wrist_pitch_joint",
        "left_wrist_yaw_joint": "right_wrist_yaw_joint",
        "right_shoulder_pitch_joint": "left_shoulder_pitch_joint",
        "right_shoulder_roll_joint": "left_shoulder_roll_joint",
        "right_shoulder_yaw_joint": "left_shoulder_yaw_joint",
        "right_elbow_joint": "left_elbow_joint",
        "right_wrist_roll_joint": "left_wrist_roll_joint",
        "right_wrist_pitch_joint": "left_wrist_pitch_joint",
        "right_wrist_yaw_joint": "left_wrist_yaw_joint",
        # Central joints (map to themselves)
        "waist_yaw_joint": "waist_yaw_joint",
        "waist_roll_joint": "waist_roll_joint",
        "waist_pitch_joint": "waist_pitch_joint",
    },
    flip_sign_joint_names=[
        # Hip roll and yaw joints
        "left_hip_roll_joint",
        "left_hip_yaw_joint",
        "right_hip_roll_joint",
        "right_hip_yaw_joint",
        # Ankle roll joints
        "left_ankle_roll_joint",
        "right_ankle_roll_joint",
        # Waist roll and yaw joints
        "waist_roll_joint",
        "waist_yaw_joint",
        # Shoulder roll and yaw joints
        "left_shoulder_roll_joint",
        "left_shoulder_yaw_joint",
        "right_shoulder_roll_joint",
        "right_shoulder_yaw_joint",
        # Wrist roll and yaw joints
        "left_wrist_roll_joint",
        "left_wrist_yaw_joint",
        "right_wrist_roll_joint",
        "right_wrist_yaw_joint",
    ],
    apply_dof_armature_in_isaacgym=True,
    contact_pairs_multiplier=16,
    control=RobotControlConfig(
        control_type="P",
        stiffness={
            "hip_yaw": 40.179238471,  # STIFFNESS_7520_14
            "hip_roll": 99.098427777,  # STIFFNESS_7520_22
            "hip_pitch": 40.179238471,  # STIFFNESS_7520_14
            "knee": 99.098427777,  # STIFFNESS_7520_22
            "ankle_pitch": 28.501246196,  # 2*STIFFNESS_5020
            "ankle_roll": 28.501246196,  # 2*STIFFNESS_5020
            "waist_yaw": 40.179238471,  # STIFFNESS_7520_14
            "waist_roll": 28.501246196,  # 2*STIFFNESS_5020
            "waist_pitch": 28.501246196,  # 2*STIFFNESS_5020
            "shoulder_pitch": 14.250623098,  # STIFFNESS_5020
            "shoulder_roll": 14.250623098,  # STIFFNESS_5020
            "shoulder_yaw": 14.250623098,  # STIFFNESS_5020
            "elbow": 14.250623098,  # STIFFNESS_5020
            "wrist_roll": 14.250623098,  # STIFFNESS_5020
            "wrist_pitch": 16.778327481,  # STIFFNESS_4010
            "wrist_yaw": 16.778327481,  # STIFFNESS_4010
        },
        damping={
            "hip_yaw": 2.557889765,  # DAMPING_7520_14
            "hip_roll": 6.308801854,  # DAMPING_7520_22
            "hip_pitch": 2.557889765,  # DAMPING_7520_14
            "knee": 6.308801854,  # DAMPING_7520_22
            "ankle_pitch": 1.814445687,  # 2*DAMPING_5020
            "ankle_roll": 1.814445687,  # 2*DAMPING_5020
            "waist_yaw": 2.557889765,  # DAMPING_7520_14
            "waist_roll": 1.814445687,  # 2*DAMPING_5020
            "waist_pitch": 1.814445687,  # 2*DAMPING_5020
            "shoulder_pitch": 0.907222843,  # DAMPING_5020
            "shoulder_roll": 0.907222843,  # DAMPING_5020
            "shoulder_yaw": 0.907222843,  # DAMPING_5020
            "elbow": 0.907222843,  # DAMPING_5020
            "wrist_roll": 0.907222843,  # DAMPING_5020
            "wrist_pitch": 1.068141502,  # DAMPING_4010
            "wrist_yaw": 1.068141502,  # DAMPING_4010
        },
        action_scale=0.25,  # 0.25 for locomotion, 1.0 for whole body tracking
        action_clip_value=100.0,
        clip_actions=True,
        clip_torques=True,
    ),
    asset=RobotAssetConfig(
        asset_root="@holosoma/data/robots",
        collapse_fixed_joints=True,
        replace_cylinder_with_capsule=True,
        flip_visual_attachments=False,
        armature=0.001,
        thickness=0.01,
        max_angular_velocity=1000.0,
        max_linear_velocity=1000.0,
        angular_damping=0.0,
        linear_damping=0.0,
        urdf_file="g1/g1_29dof.urdf",
        usd_file=None,
        xml_file="g1/g1_29dof.xml",
        robot_type="g1_29dof",
        enable_self_collisions=False,
        default_dof_drive_mode=3,
        fix_base_link=False,
    ),
    bridge=RobotBridgeConfig(
        sdk_type="unitree",
        motor_type="serial",
    ),
)

t1_29dof_waist_wrist = RobotConfig(
    num_bodies=32,
    dof_obs_size=29,
    actions_dim=29,
    policy_obs_dim=-1,
    critic_obs_dim=-1,
    algo_obs_dim_dict={},
    key_bodies=["left_foot_contact_point", "right_foot_contact_point"],
    num_feet=2,
    foot_body_name="foot_link",
    foot_height_name="foot_contact_point",
    knee_name="Shank",
    torso_name="Trunk",
    dof_names=[
        "AAHead_yaw",
        "Head_pitch",
        "Left_Shoulder_Pitch",
        "Left_Shoulder_Roll",
        "Left_Elbow_Pitch",
        "Left_Elbow_Yaw",
        "Left_Wrist_Pitch",
        "Left_Wrist_Yaw",
        "Left_Hand_Roll",
        "Right_Shoulder_Pitch",
        "Right_Shoulder_Roll",
        "Right_Elbow_Pitch",
        "Right_Elbow_Yaw",
        "Right_Wrist_Pitch",
        "Right_Wrist_Yaw",
        "Right_Hand_Roll",
        "Waist",
        "Left_Hip_Pitch",
        "Left_Hip_Roll",
        "Left_Hip_Yaw",
        "Left_Knee_Pitch",
        "Left_Ankle_Pitch",
        "Left_Ankle_Roll",
        "Right_Hip_Pitch",
        "Right_Hip_Roll",
        "Right_Hip_Yaw",
        "Right_Knee_Pitch",
        "Right_Ankle_Pitch",
        "Right_Ankle_Roll",
    ],
    upper_dof_names=[
        "AAHead_yaw",
        "Head_pitch",
        "Left_Shoulder_Pitch",
        "Left_Shoulder_Roll",
        "Left_Elbow_Pitch",
        "Left_Elbow_Yaw",
        "Left_Wrist_Pitch",
        "Left_Wrist_Yaw",
        "Left_Hand_Roll",
        "Right_Shoulder_Pitch",
        "Right_Shoulder_Roll",
        "Right_Elbow_Pitch",
        "Right_Elbow_Yaw",
        "Right_Wrist_Pitch",
        "Right_Wrist_Yaw",
        "Right_Hand_Roll",
    ],
    upper_left_arm_dof_names=[
        "Left_Shoulder_Pitch",
        "Left_Shoulder_Roll",
        "Left_Elbow_Pitch",
        "Left_Elbow_Yaw",
        "Left_Wrist_Pitch",
        "Left_Wrist_Yaw",
        "Left_Hand_Roll",
    ],
    upper_right_arm_dof_names=[
        "Right_Shoulder_Pitch",
        "Right_Shoulder_Roll",
        "Right_Elbow_Pitch",
        "Right_Elbow_Yaw",
        "Right_Wrist_Pitch",
        "Right_Wrist_Yaw",
        "Right_Hand_Roll",
    ],
    lower_dof_names=[
        "Waist",
        "Left_Hip_Pitch",
        "Left_Hip_Roll",
        "Left_Hip_Yaw",
        "Left_Knee_Pitch",
        "Left_Ankle_Pitch",
        "Left_Ankle_Roll",
        "Right_Hip_Pitch",
        "Right_Hip_Roll",
        "Right_Hip_Yaw",
        "Right_Knee_Pitch",
        "Right_Ankle_Pitch",
        "Right_Ankle_Roll",
    ],
    has_torso=True,
    has_upper_body_dof=True,
    left_ankle_dof_names=["Left_Ankle_Pitch", "Left_Ankle_Roll"],
    right_ankle_dof_names=["Right_Ankle_Pitch", "Right_Ankle_Roll"],
    knee_dof_names=["Left_Knee_Pitch", "Right_Knee_Pitch"],
    hips_dof_names=[
        "Left_Hip_Pitch",
        "Left_Hip_Roll",
        "Left_Hip_Yaw",
        "Right_Hip_Pitch",
        "Right_Hip_Roll",
        "Right_Hip_Yaw",
    ],
    dof_pos_lower_limit_list=[
        -1.57,
        -0.35,
        -3.31,
        -1.74,
        -2.27,
        -2.27,
        -2.27,
        -2.27,
        -2.27,
        -3.31,
        -1.57,
        -2.27,
        -2.27,
        -2.27,
        -2.27,
        -2.27,
        -1.57,
        -1.8,
        -0.3,
        -1,
        0,
        -0.87,
        -0.44,
        -1.8,
        -1.57,
        -1,
        0,
        -0.87,
        -0.44,
    ],
    dof_pos_upper_limit_list=[
        1.57,
        1.22,
        1.22,
        1.57,
        2.27,
        2.27,
        2.27,
        2.27,
        2.27,
        1.22,
        1.74,
        2.27,
        2.27,
        2.27,
        2.27,
        2.27,
        1.57,
        1.57,
        1.57,
        1,
        2.34,
        0.35,
        0.44,
        1.57,
        0.3,
        1,
        2.34,
        0.35,
        0.44,
    ],
    dof_vel_limit_list=[
        12.56,
        12.56,
        18.84,
        18.84,
        18.84,
        18.84,
        18.84,
        18.84,
        18.84,
        18.84,
        18.84,
        18.84,
        18.84,
        18.84,
        18.84,
        18.84,
        10.88,
        12.5,
        10.9,
        10.9,
        11.7,
        18.8,
        12.4,
        12.5,
        10.9,
        10.9,
        11.7,
        18.8,
        12.4,
    ],
    dof_effort_limit_list=[
        7,
        7,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        18,
        30,
        45,
        30,
        30,
        60,
        12,
        12,
        45,
        30,
        30,
        60,
        12,
        12,
    ],
    dof_armature_list=[
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
        0.03,
    ],
    dof_joint_friction_list=[
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
        0.01,
    ],
    body_names=[
        "Trunk",
        "H1",
        "H2",
        "AL1",
        "AL2",
        "AL3",
        "AL4",
        "AL5",
        "AL6",
        "left_hand_link",
        "AR1",
        "AR2",
        "AR3",
        "AR4",
        "AR5",
        "AR6",
        "right_hand_link",
        "Waist",
        "Hip_Pitch_Left",
        "Hip_Roll_Left",
        "Hip_Yaw_Left",
        "Shank_Left",
        "Ankle_Cross_Left",
        "left_foot_link",
        "left_foot_contact_point",
        "Hip_Pitch_Right",
        "Hip_Roll_Right",
        "Hip_Yaw_Right",
        "Shank_Right",
        "Ankle_Cross_Right",
        "right_foot_link",
        "right_foot_contact_point",
    ],
    terminate_after_contacts_on=["Waist", "Shoulder", "Hip", "Trunk", "Head"],
    penalize_contacts_on=["Trunk", "H1", "H2", "AL", "AR", "Waist", "Hip", "Shank", "Ankle"],
    init_state=RobotInitState(
        pos=[0.0, 0.0, 0.68],  # x,y,z [m]
        rot=[0.0, 0.0, 0.0, 1.0],  # x,y,z,w [quat]
        lin_vel=[0.0, 0.0, 0.0],  # x,y,z [m/s]
        ang_vel=[0.0, 0.0, 0.0],  # x,y,z [rad/s]
        default_joint_angles={
            "AAHead_yaw": 0.0,
            "Head_pitch": 0.0,
            "Left_Shoulder_Pitch": 0.2,
            "Left_Shoulder_Roll": -1.35,
            "Left_Elbow_Pitch": 0.0,
            "Left_Elbow_Yaw": -0.5,
            "Left_Wrist_Pitch": 0.0,
            "Left_Wrist_Yaw": 0.0,
            "Left_Hand_Roll": 0.0,
            "Right_Shoulder_Pitch": 0.2,
            "Right_Shoulder_Roll": 1.35,
            "Right_Elbow_Pitch": 0.0,
            "Right_Elbow_Yaw": 0.5,
            "Right_Wrist_Pitch": 0.0,
            "Right_Wrist_Yaw": 0.0,
            "Right_Hand_Roll": 0.0,
            "Waist": 0.0,
            "Left_Hip_Pitch": -0.2,
            "Left_Hip_Roll": 0.0,
            "Left_Hip_Yaw": 0.0,
            "Left_Knee_Pitch": 0.4,
            "Left_Ankle_Pitch": -0.25,
            "Left_Ankle_Roll": 0.0,
            "Right_Hip_Pitch": -0.2,
            "Right_Hip_Roll": 0.0,
            "Right_Hip_Yaw": 0.0,
            "Right_Knee_Pitch": 0.4,
            "Right_Ankle_Pitch": -0.25,
            "Right_Ankle_Roll": 0.0,
        },
    ),
    randomize_link_body_names=[
        "Trunk",
        "Hip_Pitch_Left",
        "Hip_Roll_Left",
        "Hip_Yaw_Left",
        "Shank_Left",
        "Ankle_Cross_Left",
        "left_foot_link",
        "Hip_Pitch_Right",
        "Hip_Roll_Right",
        "Hip_Yaw_Right",
        "Shank_Right",
        "Ankle_Cross_Right",
        "right_foot_link",
    ],
    waist_dof_names=["Waist"],
    waist_yaw_dof_name="Waist",
    waist_roll_dof_name=None,
    waist_pitch_dof_name=None,
    arm_dof_names=[
        "Left_Shoulder_Pitch",
        "Left_Shoulder_Roll",
        "Left_Elbow_Pitch",
        "Left_Elbow_Yaw",
        "Left_Wrist_Pitch",
        "Left_Wrist_Yaw",
        "Left_Hand_Roll",
        "Right_Shoulder_Pitch",
        "Right_Shoulder_Roll",
        "Right_Elbow_Pitch",
        "Right_Elbow_Yaw",
        "Right_Wrist_Pitch",
        "Right_Wrist_Yaw",
        "Right_Hand_Roll",
    ],
    left_arm_dof_names=[
        "Left_Shoulder_Pitch",
        "Left_Shoulder_Roll",
        "Left_Elbow_Pitch",
        "Left_Elbow_Yaw",
        "Left_Wrist_Pitch",
        "Left_Wrist_Yaw",
        "Left_Hand_Roll",
    ],
    right_arm_dof_names=[
        "Right_Shoulder_Pitch",
        "Right_Shoulder_Roll",
        "Right_Elbow_Pitch",
        "Right_Elbow_Yaw",
        "Right_Wrist_Pitch",
        "Right_Wrist_Yaw",
        "Right_Hand_Roll",
    ],
    symmetry_joint_names={
        "AAHead_yaw": "AAHead_yaw",
        "Head_pitch": "Head_pitch",
        "Left_Shoulder_Pitch": "Right_Shoulder_Pitch",
        "Left_Shoulder_Roll": "Right_Shoulder_Roll",
        "Left_Elbow_Pitch": "Right_Elbow_Pitch",
        "Left_Elbow_Yaw": "Right_Elbow_Yaw",
        "Left_Wrist_Pitch": "Right_Wrist_Pitch",
        "Left_Wrist_Yaw": "Right_Wrist_Yaw",
        "Left_Hand_Roll": "Right_Hand_Roll",
        "Right_Shoulder_Pitch": "Left_Shoulder_Pitch",
        "Right_Shoulder_Roll": "Left_Shoulder_Roll",
        "Right_Elbow_Pitch": "Left_Elbow_Pitch",
        "Right_Elbow_Yaw": "Left_Elbow_Yaw",
        "Right_Wrist_Pitch": "Left_Wrist_Pitch",
        "Right_Wrist_Yaw": "Left_Wrist_Yaw",
        "Right_Hand_Roll": "Left_Hand_Roll",
        "Waist": "Waist",
        "Left_Hip_Pitch": "Right_Hip_Pitch",
        "Left_Hip_Roll": "Right_Hip_Roll",
        "Left_Hip_Yaw": "Right_Hip_Yaw",
        "Left_Knee_Pitch": "Right_Knee_Pitch",
        "Left_Ankle_Pitch": "Right_Ankle_Pitch",
        "Left_Ankle_Roll": "Right_Ankle_Roll",
        "Right_Hip_Pitch": "Left_Hip_Pitch",
        "Right_Hip_Roll": "Left_Hip_Roll",
        "Right_Hip_Yaw": "Left_Hip_Yaw",
        "Right_Knee_Pitch": "Left_Knee_Pitch",
        "Right_Ankle_Pitch": "Left_Ankle_Pitch",
        "Right_Ankle_Roll": "Left_Ankle_Roll",
    },
    flip_sign_joint_names=[
        "AAHead_yaw",
        "Left_Shoulder_Roll",
        "Left_Elbow_Yaw",
        "Left_Wrist_Yaw",
        "Left_Hand_Roll",
        "Right_Shoulder_Roll",
        "Right_Elbow_Yaw",
        "Right_Wrist_Yaw",
        "Right_Hand_Roll",
        "Waist",
        "Left_Hip_Roll",
        "Left_Hip_Yaw",
        "Left_Ankle_Roll",
        "Right_Hip_Roll",
        "Right_Hip_Yaw",
        "Right_Ankle_Roll",
    ],
    contact_pairs_multiplier=16,
    control=RobotControlConfig(
        control_type="P",
        stiffness={
            "Head_yaw": 5,
            "Head_pitch": 5,
            "Hip_Yaw": 200,
            "Hip_Roll": 200,
            "Hip_Pitch": 200,
            "Knee": 200,
            "Ankle_Pitch": 50,
            "Ankle_Roll": 50,
            "Waist": 200,
            "Shoulder_Pitch": 20,
            "Shoulder_Roll": 20,
            "Elbow_Pitch": 20,
            "Elbow_Yaw": 20,
            "Wrist_Pitch": 20,
            "Wrist_Yaw": 20,
            "Hand_Roll": 20,
        },
        damping={
            "Head_yaw": 0.5,
            "Head_pitch": 0.5,
            "Hip_Yaw": 5,
            "Hip_Roll": 5,
            "Hip_Pitch": 5,
            "Knee": 5,
            "Ankle_Pitch": 3,
            "Ankle_Roll": 3,
            "Waist": 5,
            "Shoulder_Pitch": 0.5,
            "Shoulder_Roll": 0.5,
            "Elbow_Pitch": 0.5,
            "Elbow_Yaw": 0.5,
            "Wrist_Pitch": 0.5,
            "Wrist_Yaw": 0.5,
            "Hand_Roll": 0.5,
        },
        action_scale=0.25,
        action_clip_value=100.0,
        clip_actions=True,
        clip_torques=True,
    ),
    asset=RobotAssetConfig(
        asset_root="@holosoma/data/robots",
        collapse_fixed_joints=True,
        replace_cylinder_with_capsule=True,
        flip_visual_attachments=False,
        armature=0.001,
        thickness=0.01,
        max_angular_velocity=1000.0,
        max_linear_velocity=1000.0,
        angular_damping=0.0,
        linear_damping=0.0,
        urdf_file="t1/t1_29dof.urdf",
        usd_file=None,
        xml_file="t1/t1_29dof.xml",
        robot_type="t1_29dof",
        enable_self_collisions=False,
        default_dof_drive_mode=3,
        density=0.001,
        fix_base_link=False,
    ),
    bridge=RobotBridgeConfig(
        sdk_type="booster",
        motor_type="serial",
    ),
    knee_joint_min_threshold=0.35,
)

g1_29dof_w_object = replace(
    g1_29dof,
    asset=replace(
        g1_29dof.asset,
        urdf_file="g1/main_mesh_collision_halfspherehand.urdf",
    ),
    control=replace(
        g1_29dof.control,
        action_scales_by_effort_limit_over_p_gain=True,
        action_scale=0.25,
    ),
)

DEFAULTS = {
    "g1_29dof": g1_29dof,
    "t1_29dof_waist_wrist": t1_29dof_waist_wrist,
    "g1_29dof_w_object": g1_29dof_w_object,
}
