name: Pytests

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'scripts/source_*'
    types:
    - opened
    - reopened
    - synchronize

jobs:
  tests:
    strategy:
      fail-fast: false # continue on one test failing
      matrix:
        simulator: [isaacgym, isaacsim]
        multigpu: ["False"]
        # no multigpu isaacsim tests for now
        include:
        - simulator: isaacgym
          multigpu: "True"
    name: Run ${{ matrix.simulator }} Tests with ${{ matrix.multigpu == 'True' && 'multi-gpu' || 'single-gpu' }}
    runs-on:
    - codebuild-holosoma-a10g-${{ matrix.multigpu == 'True' && 'x4' || 'x1' }}-gpu-build-${{ github.run_id }}-${{ github.run_attempt }}
    continue-on-error: true
    container:
      image: 982423663241.dkr.ecr.us-west-2.amazonaws.com/holosoma-${{ matrix.simulator }}:latest
      options: "--gpus all --runtime=nvidia --shm-size=12g"
      env:
        HOLOSOMA_MULTIGPU: ${{ matrix.multigpu }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Pytest
        id: pytest
        shell: bash
        run: |
          ln -s /root/.holosoma_deps "$HOME/.holosoma_deps"
          if [[ ! -L /workspace/holosoma ]]; then
            rm -rf /workspace/holosoma
            ln -sfF "$GITHUB_WORKSPACE" /workspace/holosoma
          fi
          bash tests/ci/${{ matrix.simulator }}_ci_tests.sh

  e2e-tests:
    strategy:
      fail-fast: false # continue on one test failing
      # e2e only on isaacgym single gpu for now
      matrix:
        simulator: [isaacgym]
        multigpu: ["False"]
    name: Run ${{ matrix.simulator }} Tests end-to-end with ${{ matrix.multigpu == 'True' && 'multi-gpu' || 'single-gpu' }}
    runs-on:
    - codebuild-holosoma-a10g-${{ matrix.multigpu == 'True' && 'x4' || 'x1' }}-gpu-build-${{ github.run_id }}-${{ github.run_attempt }}
    continue-on-error: true
    container:
      # needs both hsgym and hsinference envs
      image: 982423663241.dkr.ecr.us-west-2.amazonaws.com/holosoma:latest
      options: "--gpus all --runtime=nvidia --shm-size=12g"
      env:
        HOLOSOMA_MULTIGPU: ${{ matrix.multigpu }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Pytest
        id: pytest
        shell: bash
        run: |
          ln -s /root/.holosoma_deps "$HOME/.holosoma_deps"
          if [[ ! -L /workspace/holosoma ]]; then
            rm -rf /workspace/holosoma
            ln -sfF "$GITHUB_WORKSPACE" /workspace/holosoma
          fi
          bash tests/ci/${{ matrix.simulator }}_e2e_ci_tests.sh

  inference-tests:
    name: Run Inference Unit Tests
    runs-on: codebuild-holosoma-cpu-build-${{ github.run_id }}-${{ github.run_attempt }}
    container:
      # TODO: Switch to `holosoma-inference` once it's been confirmed functional
      # image: 982423663241.dkr.ecr.us-west-2.amazonaws.com/holosoma-inference:latest
      # Until then, the inference tests will run in isaacsim env.
      image: 982423663241.dkr.ecr.us-west-2.amazonaws.com/holosoma:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run Tests
        shell: bash
        run: |
          ln -s /root/.holosoma_deps "$HOME/.holosoma_deps"
          if [[ ! -L /workspace/holosoma ]]; then
            rm -rf /workspace/holosoma
            ln -sfF "$GITHUB_WORKSPACE" /workspace/holosoma
          fi
          source scripts/source_isaacsim_setup.sh
          pip install -e src/holosoma_inference
          pytest -s src/holosoma_inference/
